spring:
  datasource:
    username: root # 数据库用户名
    password: 123456 # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://192.168.3.6:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false # 数据库地址

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml # 指定MyBatis全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml # 指定SQL映射文件位置
  type-aliases-package: com.atlp.springcloud.entities # 指定别名Entity类所在包位置